Use generated DeepCopy methods.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -111,4 +111,16 @@ else
 fi
 echo "${reset}"
 
+echo -ne "Checking for deep-copies that need updating... "
+if ! hack/verify-generated-deep-copies.sh > /dev/null; then
+  echo "${red}ERROR!"
+  echo "Some deep-copy functions need regeneration."
+  echo "To regenerate deep-copies, run:"
+  echo "  hack/update-generated-deep-copies.sh"
+  exit_code=1
+else
+  echo "${green}OK"
+fi
+echo "${reset}"
+
 exit $exit_code
