Add a gendocs pre-submit hook.

diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -80,3 +80,16 @@ if [[ "${#files_need_description[@]}" -ne 0 ]]; then
     echo
   ) >> $1
 fi
+
+if ! hack/verify-gendocs.sh > /dev/null; then
+  (
+    echo
+    echo "# *** ERROR: *** docs are out of sync between cli and markdown"
+    echo "# run hack/gendocs.sh > docs/kubectl.md to regenerate"
+    echo
+    echo "#"
+    echo "# Your commit will be aborted unless you regenerate docs."
+    echo "    COMMIT_BLOCKED_ON_GENDOCS"
+    echo
+  ) >> $1
+fi
