Run kube-proxy in Trusty in a static pod.
We copy the manifest from salt configurations, and then remove the salt
content in the file and replace the variables with values.

diff --git a/cluster/gce/trusty/node.yaml b/cluster/gce/trusty/node.yaml
--- a/cluster/gce/trusty/node.yaml
+++ b/cluster/gce/trusty/node.yaml
@@ -1,4 +1,4 @@
-From nobody Tue Aug 11 10:13:54 2015
+From nobody Tue Dec 22 10:13:54 2015
 Content-Type: multipart/mixed; boundary="===================================="
 MIME-Version: 1.0
 
@@ -29,10 +29,11 @@ script
 	config_hostname
 	echo "Configuring IP firewall rules"
 	config_ip_firewall
-	echo "Creating required directories"
-	create_dirs
 	echo "Downloading kube-env file"
 	download_kube_env
+	echo "Creating required directories"
+	. /etc/kube-env
+	create_dirs
 	echo "Creating kubelet kubeconfig file"
 	create_kubelet_kubeconfig
 	echo "Creating kube-proxy kubeconfig file"
@@ -96,6 +97,7 @@ script
 	set -o nounset
 
 	. /etc/kube-configure.sh
+	. /etc/kube-env
 	install_kube_binary_config
 end script
 
@@ -148,42 +150,6 @@ post-stop exec sleep 10
 MIME-Version: 1.0
 Content-Type: text/upstart-job; charset="us-ascii"
 Content-Transfer-Encoding: 7bit
-Content-Disposition: attachment; filename="kube-proxy.conf"
-
-#upstart-job
-
-description "Start kube-proxy service"
-
-start on stopped kube-install-minion and stopped kube-install-packages
-
-respawn
-
-script
-	set -o errexit
-	set -o nounset
-
-	. /etc/kube-env
-	ARGS="--v=2"
-	if [ -n "${KUBEPROXY_TEST_ARGS:-}" ]; then
-		ARGS="${KUBEPROXY_TEST_ARGS}"
-	fi
-	BINARY_PATH="/usr/bin/kube-proxy"
-	if [ "${TEST_CLUSTER:-}" = "true" ]; then
-		BINARY_PATH="/usr/local/bin/kube-proxy"
-	fi
-	${BINARY_PATH} \
-		--master=https://${KUBERNETES_MASTER_NAME} \
-		--kubeconfig=/var/lib/kube-proxy/kubeconfig \
-		${ARGS}
-end script
-
-# Wait for 10s to start kube-proxy again.
-post-stop exec sleep 10
-
---====================================
-MIME-Version: 1.0
-Content-Type: text/upstart-job; charset="us-ascii"
-Content-Transfer-Encoding: 7bit
 Content-Disposition: attachment; filename="kube-docker.conf"
 
 #upstart-job
@@ -200,7 +166,61 @@ script
 	set -o nounset
 
 	. /etc/kube-configure.sh
+	. /etc/kube-env
 	restart_docker_daemon
+end script
+
+--====================================
+MIME-Version: 1.0
+Content-Type: text/upstart-job; charset="us-ascii"
+Content-Transfer-Encoding: 7bit
+Content-Disposition: attachment; filename="kube-proxy.conf"
+
+#upstart-job
+
+description "Start kube-proxy static pod"
+
+start on stopped kube-docker
+
+script
+	set -o errexit
+	set -o nounset
+
+	. /etc/kube-configure.sh
+	. /etc/kube-env
+	prepare_log_file "/var/log/kube-proxy.log"
+	# Load the docker image from file /run/kube-docker-files/kube-proxy.tar.
+	echo "Try to load docker image file kube-proxy.tar"
+	timeout 30 docker load -i /run/kube-docker-files/kube-proxy.tar
+	# Copy the manifest to /tmp to manipulate
+	tmp_file="/tmp/kube-proxy.manifest"
+	cp -f /run/kube-manifests/kubernetes/kube-proxy.manifest ${tmp_file}
+	# Remove the lines of salt configuration and replace variables with values.
+	# NOTE: Changes to variable names in cluster/saltbase/salt/kube-proxy/kube-proxy.manifest
+	# may break this upstart job.
+	sed -i "/^ *{%/d" ${tmp_file}
+	kubeconfig="--kubeconfig=\/var\/lib\/kube-proxy\/kubeconfig"
+	kube_docker_registry="gcr.io\/google_containers"
+	if [ -n "${KUBE_DOCKER_REGISTRY:-}" ]; then
+		kube_docker_registry=${KUBE_DOCKER_REGISTRY}
+	fi
+	kube_proxy_docker_tag=$(cat /run/kube-docker-files/kube-proxy.docker_tag)
+	test_args=""
+	log_level="--v=2"
+	if [ -n "${KUBEPROXY_TEST_ARGS:-}" ]; then
+		test_args="${KUBEPROXY_TEST_ARGS}"
+		# test_args should already contain log level setting.
+		log_level=""
+	fi
+	api_servers="--master=https:\/\/${KUBERNETES_MASTER_NAME}"
+	sed -i -e "s/{{kubeconfig}}/${kubeconfig}/g" ${tmp_file}
+	sed -i -e "s/{{pillar\['kube_docker_registry'\]}}/${kube_docker_registry}/g" ${tmp_file}
+	sed -i -e "s/{{pillar\['kube-proxy_docker_tag'\]}}/${kube_proxy_docker_tag}/g" ${tmp_file}
+	sed -i -e "s/{{test_args}}/${test_args}/g" ${tmp_file}
+	sed -i -e "s/{{log_level}}/${log_level}/g" ${tmp_file}
+	sed -i -e "s/{{api_servers_with_port}}/${api_servers}/g" ${tmp_file}
+
+	mv -f ${tmp_file} /etc/kubernetes/manifests/
 end script
 
 --====================================
@@ -243,7 +263,8 @@ Content-Disposition: attachment; filename="kube-node-health-monitoring.conf"
 
 description "Kubenetes node health monitoring"
 
-start on stopped kube-docker and started kube-proxy
+# The termination of kube-proxy upstart job indicates that kubelet and docker are ready.
+start on stopped kube-proxy
 
 respawn
 
@@ -254,6 +275,7 @@ script
 	# TODO(andyzheng0831): replace it with a more reliable method if possible.
 	sleep 60
 
+	. /etc/kube-env
 	sleep_seconds=10
 	max_seconds=10
 	# We simply kill the process when there is a failure. Another upstart job will automatically
@@ -263,14 +285,15 @@ script
 			echo "Docker daemon failed!"
 			pkill docker
 		fi
-		. /etc/kube-env
 		if ! curl --insecure -m ${max_seconds} -f -s https://127.0.0.1:${KUBELET_PORT:-10250}/healthz > /dev/null; then
 			echo "Kubelet is unhealthy!"
 			pkill kubelet
 		fi
 		if ! curl -m ${max_seconds} -f -s http://127.0.0.1:10249/healthz > /dev/null; then
 			echo "Kube-proxy is unhealthy!"
-			pkill kube-proxy
+			# Get the ID of kube-proxy container and then kill it.
+			container=$(docker ps -q --filter name='k8s_kube-proxy')
+			docker kill ${container}
 		fi
 		sleep ${sleep_seconds}
 	done
